server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost/PhoneBook
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true